name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=tix --cov-report=term-missing

    - name: Test CLI commands
      run: |
        tix --version
        tix --help
        tix add "Test task" -p high
        tix ls
        tix stats

    - name: Check code quality
      run: |
        # Optional: Add linting
        pip install flake8
        flake8 tix/ --max-line-length=100 --ignore=E501 || true